INSERT INTO VAT_RATE (VAT_CODE, VAT_RATE) VALUES ('A', 22);
INSERT INTO VAT_RATE (VAT_CODE, VAT_RATE) VALUES ('B', 8);
INSERT INTO VAT_RATE (VAT_CODE, VAT_RATE) VALUES ('C', 5);
INSERT INTO VAT_RATE (VAT_CODE, VAT_RATE) VALUES ('D', 3);
INSERT INTO VAT_RATE (VAT_CODE, VAT_RATE) VALUES ('E', 0);


INSERT INTO CUSTOMER(CUST_ID,CUST_NAME) VALUES (1,'CUST 1');
INSERT INTO CUSTOMER(CUST_ID,CUST_NAME) VALUES (2,'CUST 2');
INSERT INTO CUSTOMER(CUST_ID,CUST_NAME) VALUES (3,'CUST 3');
INSERT INTO CUSTOMER(CUST_ID,CUST_NAME) VALUES (4,'CUST 4');