CREATE TABLE VAT_RATE(VAT_CODE VARCHAR2(10) NOT NULL, VAT_RATE NUMBER NOT NULL);
CREATE TABLE CUSTOMER(CUST_ID NUMBER NOT NULL, CUST_NAME VARCHAR2(100));
CREATE TABLE INVOICE(INV_NO NUMBER NOT NULL, INV_DATE DATE NOT NULL, INV_CUST_ID NUMBER NOT NULL);
CREATE TABLE INVOICE_POSITION(POS_INV_NO NUMBER NOT NULL,POS_NO NUMBER NOT NULL,POS_VAT_CODE VARCHAR2(10) NOT NULL,
                              POS_QTY NUMBER, POS_PRICE NUMBER, POS_DESC VARCHAR2(100));